// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shops": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "샵 목록을 조회하는 API 입니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "샵 목록 조회 ✅",
                "responses": {
                    "200": {
                        "description": "샵 목록 응답 값",
                        "schema": {
                            "$ref": "#/definitions/tester.ListShopsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "tester.ListShopsResponse": {
            "type": "object",
            "properties": {
                "shopsV1": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tester.ShopResponse"
                    }
                },
                "shopsV2": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tester.ShopResponse"
                    }
                },
                "shopsV3": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tester.ShopResponse"
                    }
                }
            }
        },
        "tester.ShopResponse": {
            "type": "object",
            "required": [
                "shopID",
                "shopName"
            ],
            "properties": {
                "shopID": {
                    "description": "샵 ID",
                    "type": "string",
                    "example": "63ec5ccff19921e0414902b7"
                },
                "shopName": {
                    "type": "string",
                    "example": "스토어 쟈넬"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
